[project]
name = "etl2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.11",
    "requests>=2.32.3",
    "reverse-geocode>=1.6.5",
    "ruff>=0.9.10",
    "sqlalchemy>=2.0.39",
]
